// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cacher

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCacher creates a new instance of MockCacher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacher[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacher[T] {
	mock := &MockCacher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacher is an autogenerated mock type for the Cacher type
type MockCacher[T any] struct {
	mock.Mock
}

type MockCacher_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockCacher[T]) EXPECT() *MockCacher_Expecter[T] {
	return &MockCacher_Expecter[T]{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockCacher
func (_mock *MockCacher[T]) Clear(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacher_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockCacher_Clear_Call[T any] struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacher_Expecter[T]) Clear(ctx interface{}) *MockCacher_Clear_Call[T] {
	return &MockCacher_Clear_Call[T]{Call: _e.mock.On("Clear", ctx)}
}

func (_c *MockCacher_Clear_Call[T]) Run(run func(ctx context.Context)) *MockCacher_Clear_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacher_Clear_Call[T]) Return(err error) *MockCacher_Clear_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacher_Clear_Call[T]) RunAndReturn(run func(ctx context.Context) error) *MockCacher_Clear_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCacher
func (_mock *MockCacher[T]) Delete(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCacher_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCacher_Delete_Call[T any] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCacher_Expecter[T]) Delete(ctx interface{}, key interface{}) *MockCacher_Delete_Call[T] {
	return &MockCacher_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockCacher_Delete_Call[T]) Run(run func(ctx context.Context, key string)) *MockCacher_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacher_Delete_Call[T]) Return(err error) *MockCacher_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCacher_Delete_Call[T]) RunAndReturn(run func(ctx context.Context, key string) error) *MockCacher_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// DeleteByPrefix provides a mock function for the type MockCacher
func (_mock *MockCacher[T]) DeleteByPrefix(ctx context.Context, prefix string) (int, error) {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByPrefix")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (int, error)); ok {
		return returnFunc(ctx, prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) int); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacher_DeleteByPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByPrefix'
type MockCacher_DeleteByPrefix_Call[T any] struct {
	*mock.Call
}

// DeleteByPrefix is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix string
func (_e *MockCacher_Expecter[T]) DeleteByPrefix(ctx interface{}, prefix interface{}) *MockCacher_DeleteByPrefix_Call[T] {
	return &MockCacher_DeleteByPrefix_Call[T]{Call: _e.mock.On("DeleteByPrefix", ctx, prefix)}
}

func (_c *MockCacher_DeleteByPrefix_Call[T]) Run(run func(ctx context.Context, prefix string)) *MockCacher_DeleteByPrefix_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCacher_DeleteByPrefix_Call[T]) Return(n int, err error) *MockCacher_DeleteByPrefix_Call[T] {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCacher_DeleteByPrefix_Call[T]) RunAndReturn(run func(ctx context.Context, prefix string) (int, error)) *MockCacher_DeleteByPrefix_Call[T] {
	_c.Call.Return(run)
	return _c
}

// GetOrFetch provides a mock function for the type MockCacher
func (_mock *MockCacher[T]) GetOrFetch(ctx context.Context, key string, ttl time.Duration, fetchFn FetchFunc[T]) (T, error) {
	ret := _mock.Called(ctx, key, ttl, fetchFn)

	if len(ret) == 0 {
		panic("no return value specified for GetOrFetch")
	}

	var r0 T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, FetchFunc[T]) (T, error)); ok {
		return returnFunc(ctx, key, ttl, fetchFn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration, FetchFunc[T]) T); ok {
		r0 = returnFunc(ctx, key, ttl, fetchFn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration, FetchFunc[T]) error); ok {
		r1 = returnFunc(ctx, key, ttl, fetchFn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacher_GetOrFetch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrFetch'
type MockCacher_GetOrFetch_Call[T any] struct {
	*mock.Call
}

// GetOrFetch is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
//   - fetchFn FetchFunc[T]
func (_e *MockCacher_Expecter[T]) GetOrFetch(ctx interface{}, key interface{}, ttl interface{}, fetchFn interface{}) *MockCacher_GetOrFetch_Call[T] {
	return &MockCacher_GetOrFetch_Call[T]{Call: _e.mock.On("GetOrFetch", ctx, key, ttl, fetchFn)}
}

func (_c *MockCacher_GetOrFetch_Call[T]) Run(run func(ctx context.Context, key string, ttl time.Duration, fetchFn FetchFunc[T])) *MockCacher_GetOrFetch_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		var arg3 FetchFunc[T]
		if args[3] != nil {
			arg3 = args[3].(FetchFunc[T])
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCacher_GetOrFetch_Call[T]) Return(v T, err error) *MockCacher_GetOrFetch_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockCacher_GetOrFetch_Call[T]) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration, fetchFn FetchFunc[T]) (T, error)) *MockCacher_GetOrFetch_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ItemCount provides a mock function for the type MockCacher
func (_mock *MockCacher[T]) ItemCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ItemCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacher_ItemCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ItemCount'
type MockCacher_ItemCount_Call[T any] struct {
	*mock.Call
}

// ItemCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockCacher_Expecter[T]) ItemCount(ctx interface{}) *MockCacher_ItemCount_Call[T] {
	return &MockCacher_ItemCount_Call[T]{Call: _e.mock.On("ItemCount", ctx)}
}

func (_c *MockCacher_ItemCount_Call[T]) Run(run func(ctx context.Context)) *MockCacher_ItemCount_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCacher_ItemCount_Call[T]) Return(n int, err error) *MockCacher_ItemCount_Call[T] {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockCacher_ItemCount_Call[T]) RunAndReturn(run func(ctx context.Context) (int, error)) *MockCacher_ItemCount_Call[T] {
	_c.Call.Return(run)
	return _c
}
